# APS--Diario-2026
## Amauri Rafael Antunes Rosa Silidonio

## Aula 1 e Aula 2 - Primeiras duas semanas de aula (Não compareci as aulas)
Na primeira aula o professor falou/apresentou sobre a disciplina, apresentação da matéria, etc. Na segunda aula já deu inicio no conteúdo da aula falando sobre o Ciclo de vida do software que é o processo da criação até o software ficar pronto. Os modelos de desenvolvimento que são cascata: só passa pra próxima fase quando terminar a anterior, incremental: o sistema é feito por partes (incrementos), espiral: foca em analise e riscos, iterativo: você vai melhorando os ciclos a cada versão, etc. Foi passado também sobre as metodologias que são as formas de trabalhar diferente de modelo e tambem os métodos Scrum (é o jeito de trabalhar em curtar etapas que são sprints) e Kanban (é um jeito de organizar o trabalho com o visual), como faltei nessas duas primeiras aulas acabei ficando perdido quando fui na terceira semana, mas vou falar sobre isso nas dificuldades que eu tive.

## Aula 3 - 04/03
Vimos sobre levantamento de requisitos, entendi que é a fase de coletar as informações necessárias para saber oque o sistema deve fazer, nessa aula a atividade foi pesquisar sobre as técnicas de levantamento, que são: entrevista que fica mais detalhada se as perguntas forem bem feitas, questionário que é rápido e em escala parecido com a entrevista mas com perguntas mais objetivas, observação ver oque acontece de verdade, documentos que é visualizar regras já existentes, JAD que são trocas de ideias em grupo, protótipo que é testar ideia visualmente, etnografia onde o pesquisador é introduzido no ambiente de trabalho do sistema, workshop acontece um debate mediado para discutir sobre oque o sistema deve ter, brainstorming é uma reunião de pessoas que vão dando suas ideias de acordo com o tema. E então entender as diferenças para fazer uma tabela comparativa para assim entender quando usa cada uma delas. Depois foi introduzido outra atividade que seria feita que era de montar o plano de levantamento para definir quem usa o sistema, técnicas escolhidas, roteiro da entrevista, etc. Depois mostrado que íamos definir como a gente faria, as opções seriam entrevista na biblioteca (oque não aconteceu porque estavam em greve) ou a análise de licitação que é analisar documentos ja existentes, definiu a entrevista que não foi feita com as bibliotecárias da instituição mas foi feita com as IAs.

## Aula 4 - 11/03
Nessa aula fizemos o plano para o levantamento de dados, primeiro aprendemos sobre como o sistema funciona pra isso pesquisamos bibliotecas e sistemas parecidos depois entendemos quem usaria o sistema, definir o escopo do nosso trabalho, o escopo é tudo que o nosso projeto vai fazer e oque ele não vai (tudo isso sendo colocado no documento e GitHub da nossa equipe), definimos nossa técnica que foi a entrevista para as três IAs, e como atividade do questionário assíncrono deveríamos criar nossas perguntas dividindo as perguntas para cada uma e fomos mostrando e validando com o professor as que conseguimos na aula, depois finalizamos em casa as perguntas. Planejamos então a execução de como seria feito e o que cada um faria na entrevista realizada na próxima aula, nós fizemos a atividade porém aí vem o principal erro que não enviamos para o professor, então não obtivemos oque precisávamos desse questionário.

## Aula 5 - 18/03
Nessa aula foi dado o resultado do questionário assíncrono das equipes algo que não recebemos pois esquecemos de enviar, daí como atividade dessa aula tivemos que refinar o levantamento que seria então melhorar as perguntas, foi retomado sobre como fazer uma boa entrevista como por exemplo pedir exemplos concretos, perguntas de exceção, etc. Aqui para a gente que não entregou tivemos que correr atrás, e aqui acredito que nossa equipe realmente entrou de vez no projeto, como tínhamos perdido uma etapa a gente teria que continuar dali sem o conhecimento que algumas outras equipes possuíam por conta do questionário assíncrono. Então nessa aula fiz bastante pergunta para o professor para entender melhor, e a equipe também, fomos entendendo melhor a diferença das personas que são a Julia (estagiaria), Rosa (experiente) e Ana (chefe), foi explicado como seria a próxima atividade que seria feito a entrevista síncrona, então antes disso tivemos que refinar para chegar na próxima atividades prontos, principalmente para recuperar o tempo perdido.


## Aula 6 - 25/03
Então o dia da entrevista síncrona com as 3 personas respeitando as regras, antes da entrevista o professor deixou no GitHub as orientações para nos prepararmos pra essa entrevista melhor, então para funcionar cada membro da equipe ficou realizando uma tarefa na entrevista, eu mandando as perguntas e anotando as respostas no nosso documento e anotando observações, foi passado então que a Júlia era a melhor para perguntar sobre processos do dia a dia, Rosa perguntas para entender regras na pratica (aqui nossa principal dificuldade para entender) e Ana somente para decisões finais, e alguns erros que não podíamos cometer era perguntas genéricas, perguntar para pessoa errada, não perceber contradição e a equipe ficar parada enquanto o tempo passava, então mandamos nossas perguntas que achamos boas e anotamos as respostas e os feedbacks da Lu no nosso documento.

## Aula 7 - 01/04
Depois da entrevista síncrona era a vez de fazer o JAD, com base nos feedbacks da Lu e nas respostas das 3 deveríamos nos preparar para essa aula e fazer o JAD para acertar oque não tinha ficado claro, então também o professor deixou no GitHub orientações para essa atividade, então entendi que o JAD servia para atar pontas soltas no projeto e confirmar regras. Então essa etapa iria durar 10 minutos com todas elas juntas, foi talvez o melhor momento para nossa equipe porque foi onde fomos melhores, conseguimos validar bastante coisa principalmente das perguntas pra Rosa que não conseguimos achar nenhuma pergunta perfeita para ela então ela foi nosso principal foco, nessa atividade eu também mandei as perguntas e anotei as respostas no nosso documento. 

## Aula 8 - 08/04
Aqui foi onde foi apresentado sobre histórias de usuários, cenários e prototipação e oque é cada etapa dessa. O objetivo agora era organizar com oque já tínhamos, e ver se realmente entendemos o sistema e transformar em um protótipo de telas mas antes disso fazer as historias de usuários que são quem faz, oque acontece, qual regra importa e qual resultado de acontecer, e também para cada história os cenários dela. Dividimos para o grupo cada um fazer um módulo tipo cadastro, empréstimo, devolução, etc... tudo isso com base em tudo que já tínhamos, então não tem como ter um modulo que não obtivemos através das atividades. Minha parte foi o modulo de cadastro então para realizar entendi quem que cadastrava o usuário que no caso é a bibliotecária, oque cada tipo de usuário tem de diferente do outro (professor, aluno e funcionário) com base no que já tínhamos, sempre bom lembrar. E também não só cadastro de usuário mas também de livros, assim a diferença de um livro e um exemplar para o sistema. E para os dois tanto o livro quanto os usuários, com historias também para editar e excluir cadastros. 

## Aula 9 - 15/04
Ultima aula antes da entrega do nosso protótipo, aqui começamos a prototipar as telas depois que validamos com o professor alguns HUs, mandamos para ele 3 historias onde ele nos deu feedback para arrumarmos alguns erros oque foi muito importante para começar as telas. Aqui eu finalizei minhas historias e terminei de validar com o professor oque consegui mostrar, foi mostrado oque esperasse do protótipo que é então não ser bonito mas sim mostrar fluxo e mostrar oque entendemos do sistema e oque conseguimos atingir, nas telas fiz a parte inteira de cadastros desde usuários a livros, e cada um ficou responsável por alguma tela mas sempre conversando e se ajudando pra chegar no final da melhor maneira que podíamos. Então desde a primeira aula foi construído parte a parte para chegarmos nessa etapa da melhor maneira possível, desde entender la atrás as técnicas de levantamento, etc até aqui que foi prototipar as telas.

## Observações e dificuldades:
Minha maior dificuldade foi porque eu tinha faltado nas duas primeiras aulas eu fiquei perdido (não no conteúdo mas principalmente na parte da atividade que o professor passou para os grupos fazerem que era aquela tabela para falar sobre as técnicas de levantamento de requisitos), então nesse dia eu ainda não estava na minha equipe atual, e como tinha faltado na aula da formação das equipes acabou ficando só eu e o Wellington de dupla, ele não foi no dia dessa atividade então acabou que eu sozinho tentei realizar essa atividade da tabela porém obviamente não dei conta. Ali eu corri atrás e conversei com o Wellington daí fomos cada um para uma equipe para conseguirmos realizar as atividades corretamente, a parte que não enviamos a atividade da entrevista assicrona acabou dificultando.

Eu esperava aprender muita coisa mas mais na parte teórica, porém achei muito interessante realizar as entrevistas, não esperava que teríamos que formular as perguntas, refinar e realizar, até o JAD eu não tinha ideia de como funcionava e qual a diferença para uma entrevista, mas foi uma experiência muito boa.

Se fosse recomeçar eu teria corrido atrás bem antes, mesmo faltando nas aulas eu podia ter mandado email para o professor e ter lido mais o conteúdo do GitHub, oque eu fiz mas já estava um pouco atrasado, também teria ido atrás da minha equipe desde o começo.
